// File generated by flutterfire_cli.
// This file configures Firebase for your Flutter app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Load Firebase config from environment variables or use defaults
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXAMPLEKEY', // Replace with your API key
    appId: '1:123456789:android:abcdef123456', // Replace with your app ID
    messagingSenderId: '123456789',
    projectId: 'wedding-hall-app',
    storageBucket: 'wedding-hall-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXAMPLEKEY',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'wedding-hall-app',
    storageBucket: 'wedding-hall-app.appspot.com',
    iosBundleId: 'com.example.wedding_hall_booking_app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXAMPLEKEY',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'wedding-hall-app',
    storageBucket: 'wedding-hall-app.appspot.com',
    authDomain: 'wedding-hall-app.firebaseapp.com',
  );
}
